# Generated by Django 5.2.6 on 2025-12-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='课程代码')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课程描述')),
                ('credits', models.IntegerField(default=1, verbose_name='学分')),
                ('hours', models.IntegerField(default=1, verbose_name='课时')),
                ('max_students', models.IntegerField(default=50, verbose_name='最大选课人数')),
                ('current_students', models.IntegerField(default=0, verbose_name='当前选课人数')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('academic_year', models.CharField(max_length=10, verbose_name='学年')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, verbose_name='班次代码')),
                ('classroom', models.CharField(max_length=50, verbose_name='教室')),
                ('schedule', models.CharField(max_length=100, verbose_name='上课时间')),
                ('max_students', models.IntegerField(default=50, verbose_name='最大选课人数')),
                ('current_students', models.IntegerField(default=0, verbose_name='当前选课人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '课程班次',
                'verbose_name_plural': '课程班次',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('dropped', '已退课')], default='pending', max_length=10, verbose_name='选课状态')),
                ('enroll_time', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='成绩')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
            },
        ),
    ]
